open-api: 
  key: ${OpenApiKey}

server: 
  port: 8082

spring: 
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
logging: 
  level: 
    root: OFF # OFF or INFO
    org.springframework.web: DEBUG
    com.kdk: DEBUG